data_engineering/HandyFacts/apps/HandyFacts/urls.py
from django.urls import path, include
from . import views
#from apps.HandyFacts.api.views import PropertyIdsApiView

app_name = 'handy-facts'

urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('house_post/', views.create_house, name='house_create'),
    # path('products/', views.products, name='products'),
    path('houses/', views.Houses_list.as_view(), name='houses'),
    path('graph_list/', views.GraphList.as_view(), name='graph_list'),
    path('graph/<int:graph_id>', views.graph, name='graph_detail'),
    path('graph_create_form/', views.graph_create_form, name='graph_create_form'),
    path('graph_create/', views.graph_create, name='graph_create'),
    path('get_started/', views.get_started, name='started')
    #path('api/property/id/', PropertyIdsApiView.as_view())
]

data_engineering/HandyFacts/core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.HandyFacts.urls')),
    #Path users
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('apps.Members.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
document_root = settings.STATIC_ROOT)

data_engineering/HandyFacts/apps/HandyFacts/models.py
from django.db import models

# Create your models here.
class State(models.Model):
    name = models.CharField(max_length=30)
    code = models.CharField(max_length=5)

class City(models.Model):
    name = models.CharField(max_length=50)

class Tag(models.Model):
    name = models.CharField(max_length=50)

class Property(models.Model):
    property_id = models.BigIntegerField(primary_key=True)
    longitude = models.FloatField(verbose_name='Longitude', null=True)
    latitude = models.FloatField(verbose_name='Latitude', null=True)
    postal_code = models.IntegerField(verbose_name='Postal Code')
    line = models.CharField(max_length=300, verbose_name='Line', null=True)
    fips_code = models.FloatField(verbose_name='Fips Code', null=True)
    name = models.CharField(max_length=300, verbose_name='Name', null=True)
    is_new_construction = models.BooleanField(null=True)
    is_plan = models.BooleanField(null=True)
    is_price_reduced = models.BooleanField(null=True)
    is_foreclosure = models.BooleanField(null=True)
    is_coming_soon = models.BooleanField(null=True)
    is_contigent = models.BooleanField(null=True)
    street_view_url = models.URLField(max_length=400,verbose_name='Street View')
    sqft = models.FloatField(null=True)
    baths = models.FloatField(null=True)
    lot_sqft = models.FloatField(null=True)
    year_built = models.FloatField(null=True)
    garage = models.FloatField(null=True)
    stories = models.FloatField(null=True)
    beds = models.FloatField(null=True)
    type = models.CharField(max_length=100, null=True)
    primary_photo = models.URLField(max_length=400,null=True)
    list_date = models.DateField(verbose_name='List Date')
    list_price = models.FloatField(null=True)
    status = models.CharField(max_length=50)

    state = models.ManyToManyField(State)
    city = models.ManyToManyField(City)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return f'Id: {self.property_id}-Name:{self.name}'

class Demanda(models.Model):
    Date = models.DateField() 
    AL_usa = models.FloatField() 
    AR_usa = models.FloatField() 
    AZ_usa = models.FloatField() 
    CA_usa = models.FloatField() 
    CO_usa = models.FloatField() 
    CT_usa = models.FloatField() 
    FL_usa = models.FloatField() 
    GA_usa = models.FloatField() 
    HI_usa = models.FloatField() 
    IA_usa = models.FloatField()
    ID_usa = models.FloatField() 
    IL_usa = models.FloatField() 
    IN_usa = models.FloatField() 
    KS_usa = models.FloatField() 
    KY_usa = models.FloatField() 
    LA_usa = models.FloatField() 
    MA_usa = models.FloatField() 
    MD_usa = models.FloatField() 
    MI_usa = models.FloatField() 
    MN_usa = models.FloatField() 
    MO_usa = models.FloatField() 
    NC_usa = models.FloatField()
    NE_usa = models.FloatField() 
    NM_usa = models.FloatField() 
    NV_usa = models.FloatField() 
    NY_usa = models.FloatField() 
    OH_usa = models.FloatField() 
    OK_usa = models.FloatField() 
    OR_usa = models.FloatField() 
    PA_usa = models.FloatField() 
    RI_usa = models.FloatField() 
    SC_usa = models.FloatField() 
    TN_usa = models.FloatField() 
    TX_usa = models.FloatField()
    UT_usa = models.FloatField() 
    VA_usa = models.FloatField() 
    WA_usa = models.FloatField() 
    WI_usa = models.FloatField()

    class Meta:
        db_table = 'demanda'

class Houses_for_sale(models.Model):
    property_id = models.BigIntegerField(primary_key=True)
    lon = models.FloatField(null=True)
    lat = models.FloatField(null=True)
    postal_code = models.IntegerField(null=True)
    state = models.CharField(max_length=300, null=True)
    city = models.CharField(max_length=200, null=True)
    state_code = models.CharField(max_length=200, null=True)
    line = models.CharField(max_length=300, null=True)
    fips_code = models.FloatField(null=True)
    name = models.CharField(null=True)
    is_new_construction = models.BooleanField(null=True)
    is_plan = models.BooleanField(null=True)
    is_price_reduced = models.BooleanField(null=True)
    is_foreclosure = models.BooleanField(null=True)
    is_coming_soon = models.BooleanField(null=True)
    is_contingent = models.BooleanField(null=True)
    street_view_url = models.URLField(max_length=400,null=True)
    sqft = models.FloatField(null=True)
    baths = models.FloatField(null=True)
    lot_sqft = models.FloatField(null=True)
    year_built = models.FloatField(null=True)
    garage = models.FloatField(null=True)
    stories = models.FloatField(null=True)
    beds = models.FloatField(null=True)
    type = models.CharField(null=True, max_length=200)
    primary_photo = models.TextField(null=True)
    tags = models.TextField(null=True)
    list_date = models.DateField(null=True)
    photos = models.URLField(max_length=400, null=True)
    list_price = models.FloatField(null=True)
    listing_id = models.CharField(max_length=200, null=True)
    primary = models.BooleanField(null=True)
    status = models.CharField(max_length=200, null=True)
    prediction = models.FloatField(null=True)

    class Meta:
        db_table = 'houses_for_sale'

class Houses_sold(models.Model):
    property_id = models.BigIntegerField(primary_key=True)
    lon = models.FloatField(null=True)
    lat = models.FloatField(null=True)
    postal_code = models.IntegerField(null=True)
    state = models.CharField(max_length=300, null=True)
    city = models.CharField(max_length=200, null=True)
    state_code = models.CharField(max_length=200, null=True)
    line = models.CharField(max_length=300, null=True)
    fips_code = models.FloatField(null=True)
    name = models.CharField(null=True)
    is_new_construction = models.BooleanField(null=True)
    is_plan = models.BooleanField(null=True)
    is_price_reduced = models.BooleanField(null=True)
    is_foreclosure = models.BooleanField(null=True)
    is_coming_soon = models.BooleanField(null=True)
    is_contingent = models.BooleanField(null=True)
    street_view_url = models.URLField(max_length=400,null=True)
    sqft = models.FloatField(null=True)
    baths = models.FloatField(null=True)
    lot_sqft = models.FloatField(null=True)
    year_built = models.FloatField(null=True)
    garage = models.FloatField(null=True)
    stories = models.FloatField(null=True)
    beds = models.FloatField(null=True)
    type = models.CharField(null=True, max_length=200)
    primary_photo = models.TextField(null=True)
    tags = models.TextField(null=True)
    list_date = models.DateField(null=True)
    photos = models.URLField(max_length=400, null=True)
    list_price = models.FloatField(null=True)
    listing_id = models.CharField(max_length=200, null=True)
    status = models.CharField(max_length=200, null=True)

    class Meta:
        db_table = 'houses_sold'

class Graph(models.Model):
    name = models.CharField(max_length=200)
    link = models.URLField(max_length=400)

data_engineering/HandyFacts/apps/HandyFacts/api/views.py
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.response import Response
from apps.HandyFacts import models
#from apps.HandyFacts.api.serializer import PropertySerializer

# class PropertyIdsApiView(APIView):
#     def get(self, request):
#         list_data = list(models.Property.objects.values('property_id').all())
#         list_ids = [index['property_id'] for index in list_data]
#         return Response(
#             status = status.HTTP_200_OK,
#             data = {
#                 'ids':list_ids
#             })

data_engineering/HandyFacts/apps/HandyFacts/views.py
import json
from typing import Any
from django.db.models.query import QuerySet
import pandas as pd
from . import models
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.db.models.functions import Cast
from django.db.models import F, IntegerField
from django.views.generic.list import ListView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
# Create your views here.
def index(request):
    return render(request, 'HandyFacts/index.html')

@method_decorator(login_required, name='dispatch')
class Houses_list(ListView):
    model = models.Houses_for_sale
    paginate_by = 30

    def get_queryset(self) :
        search = self.request.GET.get('search_text')
        state = self.request.GET.get('state_list')
        city = self.request.GET.get('city')
        option_price = self.request.GET.get('option_price')
        if search:
            return models.Houses_for_sale.objects.filter(
                name__icontains = search
            )
        if state:
            return models.Houses_for_sale.objects.filter(
                state = state
            )
        if city:
            return models.Houses_for_sale.objects.filter(
                city = city
            )
        if option_price:
            if option_price == 'Low to High':
                return models.Houses_for_sale.objects.all().order_by('list_price')
            elif option_price == 'High to Low':
                return models.Houses_for_sale.objects.all().order_by('-list_price')
        return models.Houses_for_sale.objects.all()

    def get_context_data(self, **kwargs: Any):
        context =  super().get_context_data(**kwargs)
        context['states'] = models.Houses_for_sale.objects.values_list('state', flat=True).distinct()
        context['cities'] = models.Houses_for_sale.objects.values_list('city', flat=True).distinct()
        
        return context
    
def about(request):
    return render(request, 'HandyFacts/about.html')

@method_decorator(login_required, name='dispatch')
class GraphList(ListView):
    model = models.Graph
    template_name = 'HandyFacts/graph_list.html'

@login_required
def graph(request, graph_id):
    graph = models.Graph.objects.get(pk=graph_id)
    return render(request, 'HandyFacts/graph.html',{
        'graph':graph
    })

@login_required
def graph_create_form(request):
    return render(request, 'HandyFacts/graph_create.html')

@login_required
def graph_create(request):
    name = request.POST['name']
    url = request.POST['url']
    graph = models.Graph(name=name, link=url)
    graph.save()
    return redirect('handy-facts:graph_list')


@csrf_exempt
def create_house(request):
    if request.method == 'GET':
        return HttpResponse('<h1>Hola vista de prueba</h1>')
    if request.method =='POST':
        data = eval(json.loads(request.body.decode('utf-8')))
        property_id = data.get('property_id')
        lon = data.get('lon')
        lat = data.get('lat')
        postal_code = data.get('postal_code')
        state = data.get('state')
        city = data.get('city')
        state_code = data.get('state_code')
        line = data.get('line')
        fips_code = data.get('fips_code')
        name = data.get('name')
        is_new_construction = data.get('is_new_construction')
        is_plan = data.get('is_plan')
        is_price_reduced = data.get('is_price_reduced')
        is_foreclosure = data.get('is_foreclosure')
        is_coming_soon = data.get('is_coming_soon')
        is_contingent = data.get('is_contingent')
        street_view_url = data.get('street_view_url')
        sqft = data.get('sqft')
        baths = data.get('baths')
        lot_sqft = data.get('lot_sqft')
        year_built = data.get('year_built')
        garage = data.get('garage')
        stories = data.get('stories')
        beds = data.get('beds')
        type = data.get('type')
        primary_photo = data.get('primary_photo')
        tags = data.get('tags')
        list_date = data.get('list_date')
        photos = data.get('photos')
        list_price = data.get('list_price')
        listing_id = data.get('listing_id')
        primary = data.get('primary')
        status = data.get('status')
        prediction = data.get('prediction')

        msj_crt = models.Houses_for_sale.objects.create(
            property_id = property_id,
            lon = lon,
            lat = lat,
            postal_code = postal_code,
            state = state,
            city = city,
            state_code = state_code,
            line = line,
            fips_code = fips_code,
            name = name,
            is_new_construction = is_new_construction,
            is_plan = is_plan,
            is_price_reduced = is_price_reduced,
            is_foreclosure = is_foreclosure,
            is_coming_soon = is_coming_soon,
            is_contingent = is_contingent,
            street_view_url = street_view_url,
            sqft = sqft,
            baths = baths,
            lot_sqft = lot_sqft,
            year_built = year_built,
            garage = garage,
            stories = stories,
            beds = beds,
            type = type,
            primary_photo = primary_photo,
            tags = tags,
            list_date = list_date,
            photos = photos,
            list_price = list_price,
            listing_id = listing_id,
            primary = primary,
            status = status,
            prediction = prediction
        )

    return JsonResponse({'message':'Created succesfuly'})

def get_started(request):
    return render(request, 'HandyFacts/get-started.html')

data_engineering/HandyFacts/apps/HandyFacts/templates/HandyFacts/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}About{% endblock title %}
{% block styles %}
<link rel="stylesheet" href="{% static 'HandyFacts/css/style.css' %}">
{% endblock styles %}
{% block content %}
<h1>About</h1>
{% endblock content %}

data_engineering/HandyFacts/apps/HandyFacts/templates/HandyFacts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'HandyFacts/css/navbar.css' %}">
    {% block styles %}
    {% endblock styles %}
</head>
<body>
    {% include 'HandyFacts/components/navbar.html' %}
    <div  class="hero">
        {% block content %}
        {% endblock content %}
    </div>
    {% block content2 %}
    {% endblock content2 %}
</body>
</html>

data_engineering/HandyFacts/apps/HandyFacts/templates/HandyFacts/get-started.html
{% extends 'HandyFacts/base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'HandyFacts/css/get-started.css' %}">
{% endblock styles %}
{% block title %}Get Started{% endblock title %}
{% block content %}
<div class="container">
    <div class="option">
        <h1 class="card-title">Starter</h1>
        <div class="card-content">
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Non libero, ex beatae nemo consectetur porro id totam, dolorem deleniti excepturi doloribus dolores debitis? Consequatur quam sequi qui, distinctio culpa non!</p>
        </div>
        <a  href="google.com" class="btn-card">Select</a>
    </div>
    <div class="option">
        <h1 class="card-title">Premium</h1>
        <div class="card-content">
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Non libero, ex beatae nemo consectetur porro id totam, dolorem deleniti excepturi doloribus dolores debitis? Consequatur quam sequi qui, distinctio culpa non!</p>
        </div>

        <a href="google.com" class="btn-card">Select</a>
        
    </div>
    <div class="option">
        <h1 class="card-title">Premium Plus</h1>
        <div class="card-content">
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Non libero, ex beatae nemo consectetur porro id totam, dolorem deleniti excepturi doloribus dolores debitis? Consequatur quam sequi qui, distinctio culpa non!</p>
        </div>
        <a  href="google.com" class="btn-card">Select</a>
    </div>
</div>
{% endblock content %}

data_engineering/HandyFacts/apps/HandyFacts/templates/HandyFacts/graph.html
{% extends 'HandyFacts/base.html' %}
{% load static %}
{% block title %}Graph{% endblock title %}
{% block styles %}
<link rel="stylesheet" href="{% static 'HandyFacts/css/graph.css' %}">
{% endblock styles %}
{% block content %}
{% endblock content %}
{% block content2 %}
<div class="container">
    <iframe class="graph" height="600" src="{{ graph.link }}" frameborder="0" allowfullscreen></iframe>
</div>
{% endblock content2 %}

data_engineering/HandyFacts/apps/HandyFacts/templates/HandyFacts/graph_create.html
{% extends 'HandyFacts/base.html' %}
{% load static %}
{% block title %}Graph{% endblock title %}
{% block styles %}
<link rel="stylesheet" href="{% static 'HandyFacts/css/graph_create.css' %}">
{% endblock styles %}
{% block content %}
{% endblock content %}
{% block content2 %}
<div class="container">
    <div>
        <h1>Create a Graph</h1>
        <form action="{% url 'handy-facts:graph_create' %}" method="POST">
            {% csrf_token %}
            <label for="name">Name:</label>
            <input type="text" name="name" id="name" required>
            <label for="url">Url:</label>
            <input type="text" name="url" id="url" required>
            <input type="submit" class="btn-submit">
        </form>
    </div>
</div>
{% endblock content2 %}

data_engineering/HandyFacts/apps/HandyFacts/templates/HandyFacts/graph_list.html
{% extends 'HandyFacts/base.html' %}
{% load static %}
{% block title %}Graph{% endblock title %}
{% block styles %}
<link rel="stylesheet" href="{% static 'HandyFacts/css/graph_list.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
{% endblock styles %}
{% block content %}
{% endblock content %}
{% block content2 %}
<div class="container">
    <div class="graph-box-container">
        {% for graph in object_list %}
        <div class="graph-box">
            <a href="{% url 'handy-facts:graph_detail' graph.id %}">{{ graph.name }}</a>
            <span class="material-symbols-outlined">
                monitoring
            </span>
        </div>
        {% endfor %}
        
    </div>
    <div class="graph-box plus">
        <a href="{% url 'handy-facts:graph_create_form' %}">+</a>
        <label for="">Create</label>
    </div>
</div>
{% endblock content2 %}

data_engineering/HandyFacts/apps/HandyFacts/templates/HandyFacts/houses_for_sale_list.html
{% extends 'HandyFacts/base.html' %}
{% load format_int_tags %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'HandyFacts/css/products.css' %}">
{% endblock styles %}
{% block title %}Products{% endblock title %}
{% block content %}
{% endblock content %}
{% block content2 %}
<div class="container">
    <div class="container-houses">
        <div class="sidebar">
            <form method="GET">
                <label for="search_text" class="sidebar-search">Search: </label>
                <input type="text" name="search_text" id="search_text" placeholder="Search by name">
                <input type="submit" value="Search">
            </form>
            <form action="">
                <label for="states_list" class="sidebar-label">State</label>
                <input type="text" list="states" name="state_list" id="state_list" class="sidebar-input">
                <datalist id="states">
                    {% for state in states %}
                    <option value="{{state}}">
                    {% endfor %}
                </datalist>

                <label for="city" class="sidebar-label">City</label>
                <input type="text"  list='cities' name="city" id="city" class="sidebar-input">
                <datalist id="cities">
                    {% for city in cities %}
                    <option value="{{ city }}">
                    {% endfor %}
                </datalist>
                <label for="">Order by Price:</label>
                <input type="text" list="options_price" name="option_price" id="option_price" class="sidebar-input">
                <datalist id="options_price">
                    <option value="Low to High">
                    <option value="High to Low">
                </datalist>               
<!-- 
                <label for="">Price</label>
                <input type="range">-->
                <input type="submit" name="" id="" value="Filter" class="sidebar-input"> 
            </form>
        </div>
        <div class="houses">
            {% for property in object_list %}
            <div class="card">
                {% if property.primary_photo %}
                <img src="{{ property.primary_photo }}" alt="">
                {% else %}
                <h1 height="10rem">No image available</h1>
                {% endif %}
                <div class="card-title">
                    <div><a href="">{{ property.name }}
                    </a></div>
                    <div><b>{{ property.list_price | format_price}}</b></div>
                </div>
                <div class="card-body">
                    <div class="info">
                        <div>State: {{ property.state }}</div>
                        <div>City: {{ property.city }}</div>
                    </div>
                    <div class="tags">
                        {% for tag in property.tags|create_list %}
                        <div>
                            {{tag | replace_and_upper}}
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>  
    <ul class="nav-pagination">
        {% if page_obj.has_previous %}
        <li>
            <a href="?page=1">&laquo; first</a>
        </li>
        <li>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        </li>
        {% endif %}
        <li>
            <a href="">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</a>
        </li>
        {% if page_obj.has_next %}
        <li>
            <a href="?page={{ page_obj.next_page_number }}">Next</a>
        </li>
        <li>

            <a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
        </li>
        {% endif %}
    </ul>
</div>



{% endblock content2 %}

data_engineering/HandyFacts/apps/HandyFacts/templates/HandyFacts/index.html
{% extends 'HandyFacts/base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'HandyFacts/css/style.css' %}">
{% endblock styles %}
{% block title %}Handy Facts{% endblock title %}
{% block content %}
<video autoplay loop muted plays-inline class="black-video" >
    <source src="{% static 'HandyFacts/video/video.mp4' %}" type="video/mp4">
</video>
<div class="content">
    <h1>Handy Facts</h1>
    <a href="{% url 'handy-facts:houses' %}">Explore</a>
</div>
{% endblock content %}